version: "3"

services:
  db:
    image: "postgres:12-alpine"
    environment:
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-postgres}"
    ports:
      - "${PGPORT:-5432}:5432"
